---
abstract: 'make the world look like a rainbow, but usefully'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'TOBYINK <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::6 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Global-Rainbow-Map
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Global::Rainbow::Map:
    file: lib/Global/Rainbow/Map.pm
    version: '0.002'
requires:
  Color::Library: '0'
  XML::LibXML: '1.70'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Global-Rainbow-Map/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Global-Rainbow-Map
  homepage: https://metacpan.org/release/Global-Rainbow-Map
  license: http://creativecommons.org/publicdomain/zero/1.0/
  repository: git://github.com/tobyink/p5-global-rainbow-map.git
version: '0.002'
